name: Deploy to AWS ECR 

on:
  push:
    branches: [main ,dev]
      
permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/git-actions-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
  
  